learning_users/basicapp/urls.py
from django.urls import path,include
from basicapp import views

app_name='basicapp'


urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login,name='user_login'),
    
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('basicapp/', include('basicapp.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/', views.special, name='special'),
    ]

learning_users/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

	user=models.OneToOneField(User,on_delete=models.CASCADE)       # contains username, pwd, first name, lastname
	#additional

	portfolio_site = models.URLField(blank=True)
	profile_pic = models.ImageField(upload_to='profile_pics', blank=True)


	class Meta:
		verbose_name =  "UserProfileInfo"
		verbose_name_plural =  "UserProfileInfos"


	def __str__(self):
		return self.user.username
    

learning_users/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User

from basicapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    # TODO: Define form fields here

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
    	model=User
    	fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):

	class Meta():

		model=UserProfileInfo
		fields=('portfolio_site','profile_pic')
    	        	

learning_users/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm, UserProfileInfoForm


from django.contrib.auth import authenticate,login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
def index(request):

	return render(request,'basicapp/index.html')

def register(request):

	registered=False

	if request.method=='POST':
		user_form=UserForm(data=request.POST)
		profile_form=UserProfileInfoForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():

			user=user_form.save()
			user.set_password(user.password)
			user.save()

			profile=profile_form.save(commit=False)
			profile.user=user

			if 'profile_pic' in request.FILES:
				profile.profile_pic=request.FILES['profile_pic']
				profile.save()
				registered= True

		else:
			print(user_form.errors, profile_form.errors)
	
	else:
		user_form=UserForm()
		profile_form=UserProfileInfoForm()


	return render(request,'basicapp/registration.html',{'user_form':user_form,'profile_form':profile_form, 'registered':registered})



def user_login(request):

	if request.method=="POST":
		
		username=request.POST.get('username')
		password=request.POST.get('password')

		user=authenticate(username=username,password=password)

		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect(reverse('index'))

			else:
				return HttpResponse('Account not active')

		else:
			print('someone tried to login and failed')
			print('username: {} and password :{} .format(username,password)')
			return HttpResponse('invalid login details supplied')

	else:
		return render(request,'basicapp/login.html', {})


@login_required
def user_logout(request):
	
	logout(request)
	return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
	return HttpResponse('you are not logged in')					

learning_users/templates/basicapp/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Homepage</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          
          <li><a class="navbar-link" href="{% url 'basicapp:register' %}">Register</a></li>

          {% if user.is_authenticated %}                   
          <li> <a class="navbar-link" href="{% url 'logout' %}">Logout </a></li>

          {% else %}
          <li><a class="navbar-link" href="{% url 'basicapp:user_login' %}">Login </a> </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">

    	{% block nav_bar %}
    	{% endblock  %}

   </div>
</body>
</html>   

learning_users/templates/basicapp/index.html
{% extends "basicapp/base.html" %}
{% block nav_bar %}
<div class="jumbotron">
	<h1 align="center"> Welcome to Homepage</h1>
</div>
{% endblock %}

learning_users/templates/basicapp/login.html
{% extends "basicapp/base.html" %}
{% block nav_bar %}
<div class="jumbotron">
	<h1> please login !</h1>
	<form action="{% url 'basicapp:user_login' %}" method="POST">
		{% csrf_token %}
		<label for="username">Username:</label>
		<input type="text"  name="username" placeholder="Enter username">
		<br>
		<label for="password">Password:</label>
		<input type="password" name="password">
		<br>
		<input type="submit" value="Login">
		
	</form>
</div>
{% endblock %}

learning_users/templates/basicapp/registration.html
{% extends "basicapp/base.html" %}
{% block nav_bar %}

<div class="jumbotron">
	<h1> welcome to Registration page</h1>

	{% if regsitered %}
	<h2>Thankyou for regsitration</h2>
	{% else %}
	<h2>Please fill out the form </h2>
	<form method="POST", enctype="multipart/form-data">
		{% csrf_token %}
		{{ user_form.as_p }}
		{{ profile_form.as_p }}
		<input type="submit" value="Register">
	</form>
	{% endif %}
	
</div>
{% endblock %}